---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcidb
  labels:
    app: hcidb
spec:
  selector:
    matchLabels:
      app: hcidb
  template:
    metadata:
      labels:
        app: hcidb
    spec:
      containers:
      - name: hcidb-frontend
        image: registry.shishov.ml/bshishov/hcidb:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hcidb
  labels:
    app: hcidb
spec:
  selector:
    app: hcidb
  ports:
    - name: hcidb-frontend
      port: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hcidb
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: hcidb
spec:
  tls:
  - hosts:
    - hci.shishov.ml
    secretName: letsencrypt-wildcard-shishov-ml-tls
  rules:
  - host: hci.shishov.ml
    http:
      paths:
        - path: /
          backend:
            serviceName: hcidb
            servicePort: 8080
