build site:
  image: node:8
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n" > ~/.ssh/config
    - echo -e "\tStrictHostKeyChecking no\n" > ~/.ssh/config
    - echo -e "\tIdentityFile ~/.ssh/id_rsa\n" > ~/.ssh/config
    - echo -e "\tUser $SSH_USER\n\n" > ~/.ssh/config
    - "rsync -rav --delete dist/ $SSH_USER@$DEPLOY_HOST:$DEPLOY_PATH"
